//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurryTry2.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FurryEntities : DbContext
    {
        public FurryEntities()
            : base("name=FurryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Shareable> Shareables { get; set; }
        public virtual DbSet<ShareableConnection> ShareableConnections { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<SpeedDate> SpeedDates { get; set; }
    }
}
