//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;

namespace FurryTry2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile : IEnumerable
    {
        public System.Guid ProfileId { get; set; }
        public string DisplayName { get; set; }
        public string Gender { get; set; }
        public string GenderSeeking { get; set; }
        public string Avatar { get; set; }
        public string AboutMe { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string JsonAttributes { get; set; }
        public System.DateTime Birthdate { get; set; }
        public IEnumerator GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}
