//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurryTry2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shareable
    {
        public System.Guid ShareablesId { get; set; }
        public string Description { get; set; }
        public int PointValue { get; set; }
        public string Avatar { get; set; }
    }
}
