//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurryTry2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareableConnection
    {
        public System.Guid ShareableConnectionId { get; set; }
        public System.Guid SenderUserId { get; set; }
        public System.Guid RecipientUserId { get; set; }
        public System.Guid SharebleId { get; set; }
    }
}
