//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurryTry2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedDate
    {
        public System.Guid UserId { get; set; }
        public System.Guid SpeedDateId { get; set; }
        public string Description { get; set; }
        public System.DateTime PostTime { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string JsonAttributes { get; set; }
        public string Title { get; set; }
    }
}
